server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bz_advertise?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12341234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  web:
    resources:
      static-locations: classpath:/static/, file:uploads/
