apiVersion: apps/v1
kind: Deployment
metadata:
  name: bz-ad-service
  labels:
    app: bz-ad-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bz-ad-service
  template:
    metadata:
      labels:
        app: bz-ad-service
    spec:
      containers:
        - name: bz-ad-service
          image: bz-ad-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8089
          env:
            - name: BZ_EDGE_SERVICE_URL
              value: http://bz-edge-service:90
